# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci(provider: "travis")
    match(readonly: true)
    number = sh('date "+%Y.%m.%d.%H%M"')
    increment_build_number(xcodeproj: "XcodeReleases.xcodeproj", build_number: number)
    build_app(scheme: "XcodeReleases")
    upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: "1489090817")
  end
end
