name: pull_request

on: pull_request

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  xcodebuild:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      run: xcodebuild build -project XcodeReleases.xcodeproj -scheme 'XcodeReleases' CODE_SIGNING_ALLOWED=NO

  swiftlint:
    name: swift_lint
    runs-on: ubuntu-18.04
    timeout-minutes: 45
    container:
      image: norionomura/swiftlint:0.33.0_swift-5.0
    steps:
      - uses: actions/checkout@v1
      - name: 'Run SwiftLint'
        run: swiftlint lint --strict