name: pull_request

on: pull_request

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  xcodebuild:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      run: xcodebuild build -project XcodeReleases.xcodeproj -scheme 'XcodeReleases' CODE_SIGNING_ALLOWED=NO

  swiftlint:
    steps:
    - uses: actions/checkout@v2
    - uses: docker://norionomura/swiftlint:latest
#        run: swiftlint lint --reporter github-actions-logging