name: pull_request

on: pull_request

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  xcodebuild:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      run: |
        set -o pipefail
        xcodebuild build -project XcodeReleases.xcodeproj -scheme 'XcodeReleases' CODE_SIGNING_ALLOWED=NO | xcpretty

  swiftlint:
    name: swift_lint
    runs-on: ubuntu-18.04
    container:
      image: norionomura/swiftlint:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run SwiftLint
        run: swiftlint lint #--strict