name: pull_request

on: pull_request

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  xcodebuild:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      run: xcodebuild build -project XcodeReleases.xcodeproj -scheme 'XcodeReleases' CODE_SIGNING_ALLOWED=NO

  swiftlint:
    using: docker
    image: norionomura/swiftlint:latest
    steps:
    - uses: actions/checkout@v2
    - name: SwiftLint
      run: swiftlint lint --reporter github-actions-logging